services:
  - type: web
    name: 3rd-ai-medical-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - tailwind.config.js
        - postcss.config.js
